name: Build native images on push to master
on:
  push:
    branches:
      - main
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle shadowJar
        run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs/modification-updater.jar
